### ISSUE TITLE
Escaping backslash

### ISSUE THREAD

**Issue by khaledhosny** [translate/pootle#3941]
It seems there is a problem with escaping backslash in translations, when I enter `\` submit, then re-open the unit it gets converted into `\\`. I’m not sure if this is the intended behaviour, but if yes then it is confusing and I don’t think it is a good idea to expose escaping to the translators, it should be handled transparently.

**Comment by khaledhosny** [comment]
See http://mozilla.locamotion.org/ar/firefox/translate/browser/chrome/browser/browser.properties.po#unit=13367660, for an example.

**Comment by iafan** [comment]
@julen, let's consider this bug a priority one. [See this note](https://www.evernote.com/shard/s1/sh/568f79bf-40c6-4f22-a3b9-c24cad9c32a8/30b932d958ab0abe) for additional context.

**Comment by julen** [comment]
@iafan mind adding the additional info right here so the reference doesn't get lost in the future?

**Comment by iafan** [comment]
Ok, here you go:

This is how the string looks like in the resources (single backslashes):
![1](https://cloud.githubusercontent.com/assets/1728158/10834425/7e9c1a5a-7e56-11e5-863c-dd02531cfa46.png)

This is how it looks like in the .po file (all backslashes are properly escaped as `\\`):
![2](https://cloud.githubusercontent.com/assets/1728158/10834427/823140dc-7e56-11e5-91cd-031ea9df925c.png)

And this is how it looks like in the Pootle UI (see that backslashes are displayed as `\\ `, while they really should be displayed as `\`).
![3](https://cloud.githubusercontent.com/assets/1728158/10834429/87bf0c8c-7e56-11e5-9555-c28bdc4c5f5d.png)

I changed the translation to: `\'` and submitted it, but when I open the unit, I see this (in the translation, the text is displayed as `\\'`):
![4](https://cloud.githubusercontent.com/assets/1728158/10834430/89e9a5a8-7e56-11e5-958f-aa48b97ddcde.png)

**Comment by julen** [comment]
After investigation, I'd say we are in front of two different bugs, one of data mangling (this report), and another one of incorrect display of escapes.

For the issue concerning this report, submitting a single backlash gets doubled. I've been able to track this down and identify it gets doubled in Django's request cycle, [where the `QueryDict` object for `request.POST` is built](https://github.com/django/django/blob/85a41b449bfe40307d1a9c482fc39dd1f82ba470/django/http/request.py#L327-L334). It calls `urllib.parse_qsl`, which in turn uses `urllib.unquote`. Unquoting doubles the backslash, and this is then saved to the unit.

To be fair I'm not entirely sure if the front-end/back-end sides should be doing something else here; I was under the impression such cases where handled by the framework. Any thoughts on the matter?

For the issue about displaying escapes, I have filed #4165.

**Comment by julen** [comment]
Still didn't figure out the root cause, however here's more specific data on the current state of things:

user input | textarea field (Python) | DB
--------------|-------------------------------|------
`\` | `\\` | `\`
`\\` | `\\` | `\`
`\\\` | `\\\\` | `\\`
`\\\\` | `\\\\` | `\\`

**Comment by dwaynebailey** [comment]
I think with ``\`` we've generally had a problem, which might or might not be related to the above issue.  That is when a user enters a single ``\`` we are not sure if that is their intention.  I.e. should we take ``\`` and escape it as ``\\``. Or is the ``\`` actually the start of an escape sequence ``\n``, ``\t``, etc.  And in the case where a user only wants a single ``\`` and they follow that with a letter that is part of a valid escape sequence, but which they don't want, what do they do?

My gut feeling would be that the DB should represent what we believe things should be and that serializing should sort things out.  But I'm not sure if we get tripped up with the difference between ``\`` and ``\\``.

Looking at Virtaal as a user case the main idea was to hide escaping from users.  To replicate that in Pootle we shouldn't have people worrying about ``\`` vs ``\\`` they should just be able to type the character that they want i.e. ``\``.

The problem we hit when we don't escape is the potential for a user (however remote) to enter a valid escape unintentionally.  The way Virtaal dealt with this was to use the ⏎ and → for return and tab so we were explicit.  But I'm not sure if we can do that in a textarea without major coding changes.

I'm not sure if I'm helping to resolve this here though.  Maybe the first step is to make the UI and DB consistent.

**Comment by julen** [comment]
You can entirely disregard my previous comments, as my understanding when debugging strings was incorrect (PEBKAC): I was interpreting the output of `repr()` as the actual string value.
```python
>>> from urllib import unquote
>>> value = unquote('foo \ bar')
>>> value
'foo \\ bar'
>>> print repr(value)
'foo \\ bar'
>>> print value
foo \ bar
```

**Comment by iafan** [comment]
> [...] in Pootle we shouldn't have people worrying about \ vs \\ they should just be able to type the character that they want i.e. \.

Exactly. We need to always treat user input as is, without trying to escape/unescape it in DB. What users sees in the translation UI is what needs to be in the DB. Of course, we need to do proper escaping/unescaping when dealing with underlying files (e.g. .po), but that part needs to be completely transparent.

> The problem we hit when we don't escape is the potential for a user (however remote) to enter a valid escape unintentionally.

This is not Pootle's problem. Ideally, when dealing with a specific file format, the converter needs to deal with escaping/unescaping. But if for some reason it is desired to translate the raw (not unescaped) string, then the translation also needs to be treated as a raw one, and translators will be following the escaping rules exposed in the source string.

**Comment by julen** [comment]
The core of the issue described here comes from the fact that [`\` is doubled](https://github.com/translate/pootle/blob/8f96754bc54d774f5879037684d40f90ac188576/pootle/apps/pootle_store/forms.py#L43) when [the text value is provided for the input textarea](https://github.com/translate/pootle/blob/8f96754bc54d774f5879037684d40f90ac188576/pootle/apps/pootle_store/forms.py#L94-L103). This also happens for other special characters such as `\n`, `\r`, and `\t`.

We were discussing this briefly with @iafan and were mentioning something along the lines that [he already commented](https://github.com/translate/pootle/issues/3941#issuecomment-153485650):
* When outputting text (in the textarea or elsewhere in the UI), we should display the DB value as it is, without applying any fancy transformation on top of it.
* The actual escaping should only happen when data is imported or serialized back to specific formats.

Note currently UI highlighting filters also have their piece of cake here, as they not only highlight special markers, but also transform the output text (e.g. `\n` is converted to `<span ...>\\n</span><br />`), effectively creating an artificial gap between how translators visually see the string and how the actual text is.

We believe any *transformations* like these are unnecessary, and need to go away, so the UI only displays the actual DB value. 
*(I must say I tried removing any filters before but the results were not satisfactory. I'll need to double-/triple-check that again.)*

It'd be good if we can confirm we are all on the same page here. Ultimately, the goal is to make it simple for translators to input the actual text, reducing the chance for surprises or accidentally incurring on errors, and as this issue displays, we are not there yet.

**Comment by dwaynebailey** [comment]
@julen I think we're on the same page.  Though I'd like to highlight some concerns.

I think the summary is this:
``Format <- any format specific escaping needs -> DB <-> UI``

With regards fancy transforms, I don't agree that doing the ``\n<br>`` adds no value, it give the translator a little more clues about how a string will flow.  It worked in Virtaal to reduce confusion and add more value.  But I think it adds a layer of confusion in trying to clean this up.  So stripping these out and just showing the string as it is :+1:.

My concern is that the DB will have its own [escaping concerns for string](http://dev.mysql.com/doc/refman/5.7/en/string-literals.html) i.e. we never actualy display the DB value, we unescape the real DB value.  Most are not an issue and can be roundtripped quite easily.  My concerns centre around ``\`` and it potential confusion as an escape like ``\n`` and how we handle those.  But that concern doesn't impact my agreement with the general idea.

**Comment by julen** [comment]
The summary reasons out well. 
Note we currently do some escaping for the DB value, however this causes issues like the one we are trying to address here.

I've been playing around code and have something that provides the expected input/output in the textarea and DB — it presents some other caveats and questions though. I'll tidy it up a bit and open up a RFC PR soon with that to see where we can go from there.
Related to this, and talking about the fancy transform, I think it's fine to visually display a new line (`<br>`) when there's an **actual** new line in the DB as well, but having a `\\n` as a marker as we currently have is just confusing. We could probably use any other type of marker as those showcased in #3350.

**Comment by unho** [comment]
Perhaps related #3869.

**Comment by julen** [comment]
I just put up some code for testing/comments in the PR linked above — it's not intended to be merged, so just treat it as a showcase of the taken direction.

There's still plenty of work to be done:
* Display of special characters needs to be reworked. In the showcased code new lines are displayed as such in source texts, however there's nothing similar for tabs (just added a simple `<pre>TAB</pre>` placeholder for now). It's maybe worth to play around having visual indicators here (a potential option is something similar to #3350).
* Highlighting logic needs to be unified so the end result is consistent (#4165).
* Copying from source to target needs to be fixed.

**Comment by iafan** [comment]
I promised @julen to comment on displaying of non-printable characters: since we want to display the raw data from the database, this data may contain some unprintable characters (hard line breaks are the most common ones, but there can also be tabulation symbols, non-breakable spaces and something else). I think we need to display them in the source string, but in the way that doesn't prevent people from copy-pasting text from source to target.

#3350 is definitely something that comes to my mind. Here's the demo that implements the same rendering approach to non-printable symbols (since we're rendering this in the context of HTML, we don't need a special font here):

http://jsfiddle.net/iafan/w4tpu6q6/2/

**Comment by dwaynebailey** [comment]
@julen I managed to grab some time to test this.  I made a PO files with some potential escapes.  I have the following observations:

* Newlines in source test.  \n is a problem if it appears at the end of a line since the user is unable to determine if this is a normal line ending or a newline.
  * The same applies to the newline in the target.  The user has no visual cue that they've added a newline at the end, or that one is present.
* Similar thing with \t - the ``TAB`` marker shows how a similar marker can be helpful.  But again if its at the end of a sentence you can't see it.
  * In a string you are unsure if its a space or a tab.
* \r\n - which probably shouldn't exist but does - no way to specify that as you simply see a newline.  Its only one char in the UI anyway.
* \ at the end of the line and in a sentence seems to work just fine.

I didn't test any input of strings.

@iafan thanks for the jsfiddle example.  It seems the easy part is displaying the source string.  I'm not 100% sure I like it being textual, I'd rather have icons or unicode chars to show these markers.  The issues I see are these two:

1. You need to be able to copy the special characters from source to target
2. You can't see the special characters in the target.  With the user manually entering \t and \n at least they could actually see things.  So without visual clues you don't know what character you put there or even if it is a special character e.g. nbsp.

Trust that gives some enlightenment.

**Comment by iafan** [comment]
> I'm not 100% sure I like it being textual, I'd rather have icons or unicode chars to show these markers.

Unfortunately, there are not so many special unprintable characters that you can represent using special Unicode characters in a way that the user will understand (Enter, non-breakable space, tab). I want to have a mechanism that would work for any kinds of unprintable characters first; if at some point  we decide to have a graphical representation for certain common characters, then we can always add that on top of the existing mechanism.

> You need to be able to copy the special characters from source to target
> You can't see the special characters in the target.

Yes, absolutely. These characters are copied now on manual copy-paste, but this case needs to be combined with approach from #3350 to display such characters in the editor. Also, nothing prevents us from having all unprintable characters to work as 'placeables' (clickable targets that allow to quickly insert their values into the editor).

**Comment by dwaynebailey** [comment]
@iafan 
Re getting basic right in text and adding icons later as/if needed :+1:

I couldn't replicate manual copy and paste, it didn't work for me in the jsfiddle example.  But if that's known then its just an issue in the demo.  But it seems this is on you radar so I'm good with that.

**Comment by iafan** [comment]
Looks like copy-pasting special symbols doesn't work in Firefox; it does in Chrome.

FWIW, this is how the visual representation of certain characters could look like: http://jsfiddle.net/iafan/w4tpu6q6/

**Comment by dwaynebailey** [comment]
@julen some quick observations from your last push. Some might be things not implemented or that you are already aware of.  I might be repeating myself as I can't remember all I wrote in the last comment and would rather give you a fresh view.

* Context lines. These look good. The use of text instead of escapes works, even if they might be placeholders for something else later.
  * \r\n -> LF - not sure if that was intentional but it works and makes things easier for the localiser

* Source text.
  * Not showing LF is problematic I think as it's different from the context lines.  I assume this is intentional as TAB is shown.  Also you don't know there is a LF if its at the end of the line or in fact why the lines are split if you don't have the LF marker.

* Target text
  * You can't see the markers
  * Copy source to target doesn't work.

* TM
  * Looks good and matches the rest
  * Hard to see the strike out through the markers
  * There is still special rendering of leading space with red squiggles.
  * Where source had LF between two words and TM match has TAB between same two words.  LF is striked out, as expected.  But we still retain the \n in the rendering (I assume because source text is the base from which we show the difference).  I'm really not sure which correct. Just highlighting as something to check and think about.

* Spaces
  * Leading and trailing space is still using red squiggles.  It probably wants to be part of these changes
  * Two trailing spaces leads to ``<>``
  * NBSP isn't highlighted.
  * Copy src to tgt and NBSP becomes SP

* Other
  * Undo after a copy leaves unit fuzzy.

**Comment by julen** [comment]
Thank you for the input @dwaynebailey — note the PR was still rough around the edges, I only made a push of my local changes the other day so I could set it up on our staging server. Now I have pushed more changes, unifying all highlighting logic in a single place (fixes #4165 basically).

Because of this latest change, the diff highlighting has currently the same behavior in TM matches and user suggestions, therefore displaying the part that was removed and the part that was added. Unless I'm checking it wrong, user suggestions previously displayed only the part that was added. Based on the feedback, I'm happy to make that behavior adjust selectively.

LF is definitely shown in source texts. In fact, and as already mentioned, all the highlighting logic is now shared. It might be that you were looking at a cached rendering of a editing unit, therefore you were getting a stale rendering for the unit.

Regarding the target text, I'm afraid we won't be able to display any markers or anything fancy as long as we use regular `textarea` elements. This is a whole topic on its own, and I'd leave it aside from this issue.

I have replaced the red squiggles in favor of subtle open boxes, and multiple leading/intermediate/trailing spaces are displayed in such fashion. NBSP is highlighted as well. 
*(NBSP becoming SP is an optical illusion in Firefox ([check bug 359303](https://bugzilla.mozilla.org/show_bug.cgi?id=359303); I've been bitten by this too and spent a lot of time debugging), however NBSP ends up properly in the textarea.)*

Pending:
* Figuring out how to do copying properly. We have the actual source texts in the client, so making the copy button work is not a big deal. I'm a little bit lost when it comes to regular text copying with the mouse though, as browsers exhibit different behavior when there's content generated via pseudo-elements. Considering this limitation, is the copy button good enough?
* Inputting an actual tab using the keyboard's physical tab key. Currently it'll switch focus, following browsers' default behavior. Given that it's not very common to find actual `\t`s in source texts (at least in my experience), I'm not sure how important it is to address this as part of this issue though.

**Comment by julen** [comment]
In order to avoid this from getting stalled, I'd love to hear your thoughts on the current state of things @iafan @dwaynebailey.

**Comment by iafan** [comment]
> Figuring out how to do copying properly.

As I was already mentioning above, having #3350 (special font) in place would allow us to implement copy-pasting properly. Here's how it would work:

1. We have a font which has certain symbols defined in the [Private Use Area](https://en.wikipedia.org/wiki/Private_Use_Areas)
2. We get raw string from the DB and map known symbols (line feed, tab, nbsp, etc.) to the corresponding Unicode symbols our font supports. Then we display this string in both source text and in the editor, both having the support for this font. This allows us to see and copy-paste these special symbols as any other regular symbols.
3. Before saving the translation to the database, we do the reverse conversion of the private Unicode symbols to the real ones.

> Inputting an actual tab using the keyboard's physical tab key.

I don't think this is necessary, as this will break navigation, and navigation is more important. Tab is rarely, if ever, used in translatable strings, and if it's there, one would be able to select, copy and paste it as a regular visible symbol if we have this custom font in place.

**Comment by dwaynebailey** [comment]
Quick test

* Rendering in source seems fines for all my test file also browsed units.
* Copy source to target does not work, all escapes are ignored
* Copy TM results works correctly and copies escapes as expected
* Target doesn't render escapes (we all know that just want to make sure we don't forget ;)
* Clicking on the 'icon' in source copies the escapes to target correctly.
* Entering tab doesn't work
* Space highlighting is good, pre, post and double spaces are shown in source and in browse

**Comment by dwaynebailey** [comment]
@iafan 

Special font approach.  I think I like that and it should work for us.  My only concern might be RTL and its impact there, as I'm not sure how rendering engines see the private use space area in terms of meta information like punctuation, directionality, etc. If we can match closely to the original character we're faking then it should work.

Typing tab....

I think this ignore the general issue that you can't use the keyboard to enter characters.  LF likely works for us as we can press enter.  But TAB and perhaps others ar enot possible.  Reverting to hey just click ignores the advantage of speed that using a keyboard gives a translator.

I'm not sure how to solve this issue.  I'm happy to take the direction of the user must click on the symbol for now but I'd like us to agree that this isn't ideal for speed.

If the editor had autocomplete/suggest we may be able to get around this by allowing \ to bring up a list of possible special escapes.  But I don't want to force that issue into this one.

**Comment by khaledhosny** [comment]
Using PUA for BiDi neutral characters like spaces is likely to break BiDi badly as all PUA regions AFAIK are classified as strong LTR characters. But may be the bidi neutral effect can be faked using BiDi isolates, though I’m not sure how widely supported they are in browsers since it is a rather recent addition to the BiDi algorithm.

**Comment by iafan** [comment]
I'll throw together some live demo of the font approach for everybody to try. RTL is definitely the biggest potential challenge with this approach.

**Comment by iafan** [comment]
Also: there are some symbols in PUA that are considered BiDi-neutral, see e.g. http://www.kreativekorp.com/charset/unicode.php?char=F8FF

So we might just need to carefully select mappings for the font symbols in PUA range.

**Comment by unho** [comment]
Can't we consider these special characters to be placeables?

**Comment by iafan** [comment]
> Can't we consider these special characters to be placeables?

Sure, why not. This is an independent thing, though.

**Comment by iafan** [comment]
I uploaded test files here: https://www.dropbox.com/s/hcrjqsa5bge7bnu/raw_font_test.zip?dl=1

The archive contains the font, the test html page and README for Firefox users (they may require tweaking config settings to make TTF load locally; this won't be an issue for the web app).

Try playing around with editing text in these textareas, copy-pasting it, etc. There are some tests for RTL rendering, but from what I can tell rendering looks kind of good by default, and trying to make all special characters treated as RTL doesn't improve things much.

Would love to hear your feedback.

**Comment by dwaynebailey** [comment]
@iafan had a look at this, seems to work fine.  I can't say much for the RTL stuff though, I think we need @khaledhosny's input for that.

Testing
* Copying a char into the target works.
* Entering the char doesn't work.  So pressing Enter and copying a real tab don't work to produce the needed char.  That I think could lead to some confusion if we are not doing this on the fly in the target.

Some observations
* If you copy and paste from source to target, that works.  But the risk here is someone copying from the UI into some other app, that would just not render.  I'm sure there are way around, like a copy button for such, so not that worried.  Just that we should be aware of that use case.
* I'm trying to remember why we needed to do this in the PUA :)
* With things like ZWJ and such we probably want to be able to show and hide these much like in a wordprocessor, so that it is possible to read the text without confusion.
* Using colour in the PUA chars could help (but I realise that makes rendering harder).  Just would help to deemphasise special chars.
* Doing autosuggest in the target would allow us to allow keyboard input of the correct character so typing \ brings up a list of the special chars.  \n selects [CR] icon, etc.  That on top of clicking on the char in the source could fully address input.

**Comment by iafan** [comment]
@dwaynebailey I should have mentioned that this is just a static demo, with no JavaScript-based processing. It shows a) how the font is rendered (including RTL), and b) how you can copy-paste those symbols as a regular text.

On top of that, there needs to be some JS logic that will map invisible symbols to visible ones, and this logic should kick in on any change of the value. This way, when one presses Enter, or pastes some text into the textarea, it would properly adjust the display of such special symbols.

> Using colour in the PUA chars could help (but I realise that makes rendering harder). Just would help to deemphasise special chars.

We can do special char highlighting using syntax highlighters from CodeMirror. CodeMirror syntax highlighting can be used both in a textarea mode and to highlight static text (we can use this to highlight source).

**Comment by iafan** [comment]
> With things like ZWJ and such we probably want to be able to show and hide these much like in a wordprocessor, so that it is possible to read the text without confusion.

This is what the "Raw" mode is about. The idea is to display the majority of these symbols only in Raw mode. It will be only `tab`, `cr` and `lf` symbols that will be always visible.

**Comment by iafan** [comment]
> Because of this latest change, the diff highlighting has currently the same behavior in TM matches and user suggestions, therefore displaying the part that was removed and the part that was added. Unless I'm checking it wrong, user suggestions previously displayed only the part that was added. Based on the feedback, I'm happy to make that behavior adjust selectively.

I missed that one from initial @julen's comment. For user suggestions we also display the full diff (removed/added parts). So the differ rendering is consistent with similar translations.

**Comment by iafan** [comment]
@khaledhosny any feedback from you?

**Comment by julen** [comment]
We are resuming work on this, and if there's any RTL-related feedback to add on top of the previous points, we'd love to hear that @khaledhosny. Thank you!

**Comment by julen** [comment]
> But if for some reason it is desired to translate the raw (not unescaped) string, then the translation also needs to be treated as a raw one, and translators will be following the escaping rules exposed in the source string.

So if I didn't miss the point @iafan, this would somehow mean having two editor modes that behave differently:
* _smart_ editing (default), where the custom font is used and the input text is mapped to the special characters defined there for output.
* _raw_ editing, where a monospace font is used and no transformations are applied on the input/output of characters. Text is treated as-is.

**Comment by iafan** [comment]
@julen, this is how these modes are supposed to work:

1. regular mode: we map only characters which are not related to directionality.
2. "raw" mode: we map all characters, force LTR and use monospaced font.

**Comment by julen** [comment]
After reading @dwaynebailey's comment it seems there was some confusion, so [I've put up a live demo](http://julen.github.io/editor-font/) that showcases how the font would work. @iafan this already includes the last clarifications you made.

Some caveats aside (like copying text to external apps — which can be solved), I think I like the experience so far.

**Comment by iafan** [comment]
The demo looks good!

One minor amendment from me: we only want to convert spaces to dots in the Raw mode.

**Comment by iafan** [comment]
Not sure if it's the right time to report any issues with the editing (this is a demo, after all), but Ctrl+Space not only inserts space, but moves the caret to the end of the text, which is undesirable.

**Comment by khaledhosny** [comment]
I just tested @julen’s live demo above and a simple two words Arabic string gets its words reordered  because of the inserted bullet (word one to the left of word two, not the the right of it).

Generally, I don’t think replacing Unicode characters by other one will work well as far as BiDi algorithm is concerned unless the replacement character has the exact [BiDi type](http://unicode.org/reports/tr9/#Bidirectional_Character_Types) of the one it is replacing.

**Comment by julen** [comment]
@khaledhosny the bullet should not be present in the regular editing mode as @iafan mentioned above. Besides that, I didn't add specify any `dir` in the demo (was in a rush and wanted to publish it), so probably these points affect proper RTL rendering. I updated the demo page to allow switching from LTR to RTL, it would be nice if you could check it out again.

Re. BiDi, have you tested that to confirm your hunch?

Thanks again!

**Comment by khaledhosny** [comment]
The base direction (the `dir` here) should have no effect on the case above, the order of the Arabic words should be the same. Even in “raw” mode, I expect the BiDi algorithm to be applied, otherwise it will be giving misleading results.

As for BiDi, [the algorithm](http://www.unicode.org/reports/tr9/) is very sensitive it is to character properties. Even characters that would appear to work in an identical way (e.g. an Arabic and a Hebrew letter) can behave differently under certain circumstances (they have different BiDi types for a reason).

Here are some specific issues I found:
* raw mode:
    - The RTL words order above.
    - ZWJ (U+200D) has no effect on the joining behaviour, e.g. `ه‍ه`.
    - RLM (U+200F) has no effect on the text order, e.g. `١‏٢`.
    - BiDi control chars (LRO, RLO, etc.) has no effect at all, e.g. `‮abcd‬`.

* regular mode:
    - Tab screws up the text, e.g. `عربي١	عربي٢`.
    - Ditto for NBSP, e.g. `عربي ١ عربي ٢`.

I’m not sure what other characters have special treatment to test.

**Comment by julen** [comment]
@khaledhosny some characters having no effect at all is a mistake from my side in the demo (they were being replaced with the new symbols, instead of being kept along with the symbols). I reckon this should be fixed and the characters should have their effect now.

**Comment by julen** [comment]
> I’m not sure what other characters have special treatment to test.

The demo implements the following mapping extracted from @iafan's test files.
```
                      Unicode                                       Font
    ===========================================        ==============================
    Meaning                         Dec     Hex  <==>  Symbol      Dec     Hex   BiDi
    ===========================================        ==============================
    Null Character                    0    0000        NULL      57344    E000      ?
    Tabulation                        9    0009        TAB       57353    E009      ?
    Line Feed                        10    000A        LF        57354    E00A      ?
    Carriage Return                  13    000D        CR        57357    E00D      ?
    Escape                           27    001B        ESC       57371    E01B      ?
    Space                            32    0020        SPACE*    57376    E020      ?
    Non-Breaking Space              160    00A0        NBSP      57504    E0A0      ?
    ===========================================        ==============================
    Zero-Width Space               8203    200B        ZWS       61451    F00B      ?
    Zero-Width Non-Joiner          8204    200C        ZWNJ      61452    F00C      ?
    Zero-Width Joiner              8205    200D        ZWJ       61453    F00D      ?
    Left-to-Right Mark             8206    200E        LRM       61454    F00E      ?
    Right-to-Left Mark             8207    200F        RLM       61455    F00F      ?
    Left-to-Right Embedding        8234    202A        LRE       61482    F02A      ?
    Right-to-Left Embedding        8235    202B        RLE       61483    F02B      ?
    Pop-Directional Formatting     8236    202C        PDF       61484    F02C      ?
    Left-to-Right Override         8237    202D        LRO       61485    F02D      ?
    Right-to-Left Override         8238    202E        RLO       61486    F02E      ?
    Word Joiner                    8288    2060        WJ        61536    F060      ?
    ===========================================        ==============================
```

**Comment by iafan** [comment]
@khaledhosny did you also try the read-only rendering demo I provided some time ago? It should have RTL enabled.

**Comment by iafan** [comment]
> One minor amendment from me: we only want to convert spaces to dots in the Raw mode.

@julen: and yet one more amendment: it would be absolutely fabulous if you could still render spaces as dots at the beginning or the end of the string (hanging spaces).

**Comment by dwaynebailey** [comment]
So it seems that the issue @khaledhosny has raised isn't being addressed in the PUA in that the replacements don't have the exact same bidi categories.  If we had PUA matches that where in the same class as the ones we're substituting then it could work.  But it seems that they are all bid neural or something similar.

So some options:

1. We see this as an LTR solution and do something else for bidi.
2. We use a font that changes the character as is and don't use PUA.  I think once again I need reminding why we needed to use the PUA?

**Comment by iafan** [comment]
@dwaynebailey the demo Julen provided wasn't RTL-aware initially. I guess @khaledhosny just needs to re-test this again. My read-only demo was RTL-aware, and I checked that RTL rendering looks ok, but still it would be good to confirm that with Khaled.

So I believe there are no problems with this approach.

We need to use PUA simply because there's no way to provide glyphs for special characters like newlines or characters to control directionality.

**Comment by dwaynebailey** [comment]
@iafan RTL-aware how? If you mean by adding directionality I think you are missing Khaled's point about "character properties".  Our PUA chars do not have the same directionality as the ones they are replacing therefore the Bidi algorithm does not work as expected.

At least that is my interpretation of @khaledhosny's comment.

**Comment by iafan** [comment]
It just had the RTL directionality set on a control, and in my tests I didn't see problems with the Arabic tests when spaces were replaced with dots and with "LF" characters being visible. I'd like to hear the input on the tests from https://github.com/translate/pootle/issues/3941#issuecomment-165334843 before we consider something as not working properly.

**Comment by khaledhosny** [comment]
The Arabic text with dots instead of spaces in test files from https://github.com/translate/pootle/issues/3941#issuecomment-176130738 is completely broken when the direction is LTR. The RTL looks OK, but the tests are very simple (no numbers, essentially no punctuation, etc.) and since it is static I can’t try different test.

 Also the forced RTL and LTR tests are completely unintelligible, and I don’t see what they would be good for.

As far as @julen demo goes, the raised points are still applicable. The RLO case is partially fixed, in the since that it has its effect on the text, but the visible symbols are drawn on the wrong side of the text.

**Comment by iafan** [comment]
@khaledhosny thanks for running the tests. 

> The RTL looks OK, but the tests are very simple (no numbers, essentially no punctuation, etc.)

Can you provide me some text with numbers/punctuation you would like to test this on? Preferably with the screenshot of the same text so that I could visually compare the results.

> Also the forced RTL and LTR tests are completely unintelligible, and I don’t see what they would be good for.

Forced LTR will be used for the "raw" mode. The reason why this should strictly be LTR is because the raw mode is meant to allow everybody preview HTML tags and placeholder names in their unaltered form, and these are LTR by their nature. This mode is not meant to provide readable RTL text.

**Comment by julen** [comment]
Did some extensive reading on the topic... :book:

As already mentioned by others, [PUA characters are defined as BC:L](http://unicode.org/mail-arch/unicode-ml/y2011-m08/0124.html), however it seems this is [purely informative](http://unicode.org/mail-arch/unicode-ml/y2011-m08/0174.html). If you read through that thread it's unclear whether the BC for PUA characters is taken into account by OS/rendering engines — in case they do, this will be of type L. So there's the risk that PUA characters could mess things up in RTL texts.

**Comment by julen** [comment]
@khaledhosny:
> Using PUA for BiDi neutral characters like spaces is likely to break BiDi badly as all PUA regions AFAIK are classified as strong LTR characters. But may be the bidi neutral effect can be faked using BiDi isolates, though I’m not sure how widely supported they are in browsers since it is a rather recent addition to the BiDi algorithm.

So if I understood correctly, this would be a matter of wrapping our PUA characters in `FSI` and `PDI` (`\U2068\UF0xx\U2069`) to somehow _cancel_ the `L` class of the PUA characters so they could be treated as neutral.

As you comment though, this looks to be [poorly supported by browsers at the moment](https://www.w3.org/International/tests/repo/results/rli-etc). Note the support information is from March 2015, and things might have slightly changed since then. Nevertheless it seems like we are out of luck and I don't see how we could implement the font approach properly for the time being.

**Comment by iafan** [comment]
@julen I experimented with wrapping PUA characters to force RTL, but @khaledhosny says the result is bad. But even if the rendering was good, adding these extra symbols would break the natural editing flow: caret would be stuck on these unprintable characters, which is not good.

As per my previous comments, in regular mode there are only few characters that need to be visible: hanging spaces, line feeds, and tabs. For these, we can probably additionally hijack some rarely used characters in the Unicode range with `R` class. But before we do that, I'd like to have some tests that clearly show the problem, and I hope @khaledhosny can help me with that (see https://github.com/translate/pootle/issues/3941#issuecomment-177563481).

Meanwhile, you can simply implement this together with disabling any character replacement for the normal RTL mode, if everybody agrees that this is an option.

**Comment by julen** [comment]
> I experimented with wrapping PUA characters to force RTL, but @khaledhosny says the result is bad. But even if the rendering was good, adding these extra symbols would break the natural editing flow: caret would be stuck on these unprintable characters, which is not good.

I'm not sure I follow, the test files you provided have no isolate wrapping around the PUA characters. Besides, such wrapping doesn't have to make the caret stuck — the implementation is no different from adding, say, CR, where besides the symbol the actual character also needs to be preserved so the symbol actually _works_.

In any case, as already mentioned these isolates are not widely supported in browsers so it's out of the question for the time being.

While I really like the editing experience with this font in LTR mode, I'm afraid not having proper RTL+BiDi support doesn't make this a viable option unless otherwise demonstrated.

**Comment by iafan** [comment]
@khaledhosny ping (see https://github.com/translate/pootle/issues/3941#issuecomment-177563481)

**Comment by julen** [comment]
An update on this: the PR #4171 has been rebased and updated against current master, and support for copying to the clipboard has been fixed too.

From what I can tell, we are left with a couple of issues:
* Caret positioning. When the special font is altered (e.g. manually removing a `CR` symbol) the cursor doesn't preserve the expected position.
* RTL. This is more of an unknown currently and [we'd love to hear more](https://github.com/translate/pootle/issues/3941#issuecomment-177563481) from @khaledhosny.

The first one is on my radar at the moment, unfortunately much cannot be ascertained about the second one though. Also, given that the PR makes important changes to how the editing area works, seeing the overlapping with ongoing work on #2596 and taking into account the benefits brought by the changes here (improved reusability), I'd suggest we try to move forward with this now.

**Comment by khaledhosny** [comment]
I think @julen’s last comment just nailed it, modifying the underlying characters is just incompatible with how bidi works. The kind of thing done here needs to be done in a layer above character processing, but I don’t think the web allows for this (short of doing the text layout yourself and painting everything on canvas or something similar).

**Comment by julen** [comment]
@khaledhosny thank you very much for your time to reply. Forgive me if my understanding is incorrect, but it remains a bit unclear to me whether you have also considered [@iafan's comment](https://github.com/translate/pootle/issues/3941#issuecomment-177563481): truth is in regular mode only a few characters are depicted by symbols (new line, hanging+non-breaking space, tab; note the rest are displayed in raw mode, which forces LTR) and perhaps some R class characters can be used in RTL for this purpose. It'd be great to shed some light on this, thanks again!

**Comment by julen** [comment]
I rebased and updated the PR with fixes for the caret position when dealing with `CR` symbols. The special font mapping has also been adjusted to use an [Ogham spacing character](http://www.kreativekorp.com/charset/unicode.php/unicode.php?char=169B) (`\u1680`); this being BiDi neutral should potentially work fine in RTL/BiDi scenarios.

I'm looking forward to hear more on issues, although overall I feel this is in pretty solid condition.

**Comment by dwaynebailey** [comment]
Did some clicky testing on this (not looking at RTL though)

RTL comment, since the Ogham spacing character is ON (Other Neutral) I suspect it's still not going to do what you want since the Bidi algorithms are basing their actions on the depth of bidi types.  Likely ON will not be the same as BN, WS or CS which range from Neutral to Weak strength.

Clicky testing comments:

1. When you first arrive at a unit the cursor is placed at the start of the line.  Which is what we do now, it just seemed rather odd.  But fine I guess as we're doing the same thing.
2. "Three\r\n" misses CR in the source text.  Target text renders fine
3. ""Three\r\nFour" as above CR is missing in source text, target renders fine.
4. [SP][NBSP] and [NBSP][SP] the dotted space is missing or unclear
5. Cursor seems to be different vertical length from the normal text area.  Not critical but will be different from the platform and I guess unexpected.

**Comment by iafan** [comment]
@dwaynebailey 'OGHAM SPACE MARK' is actually a whitespace character (BiDi class: WS), see e.g. http://www.fileformat.info/info/unicode/char/1680/index.htm so we expect it to behave exactly as a regular space character.

**Comment by iafan** [comment]
Regarding cursor height: this is already fixed by Julen (but not included in the PR yet). You can try going to https://translate.stage.evernote.com/ and experimenting with the editor there — Julen has patched it to include the fix for the caret.

**Comment by khaledhosny** [comment]
Testing on https://translate.stage.evernote.com/, the issues I reported before seem to be still there, most importantly:
* a number before the newline gets to the left (after) it.
* the raw mode is completely unusable, Arabic text is rendered from left to right and is completely unintelligible.

Also tab is rendered as a long (EM?) dash.

**Comment by dwaynebailey** [comment]
@iafan thanks that's a clearer unicode link.  And Ogham is old so we're unlikely to hit issues with someone actually translating into Ogham.

@iafan yes, the caret look good on the staging server.

@khaledhosny I think the idea of raw mode is that things will be broken in the RTL text.  But you will be able to see things like <tags> and $variables to check that they are indeed correctly written.

@khaledhosny I think it might help if you are able to give a simple example text and how it should look, I fear without RTL reading ability most of us can't 'see' those types of issues.

**Comment by iafan** [comment]
@khaledhosny can you please confirm that the trailing/leading whitespace or multiple spaces in the middle of the string, which are rendered as visible dots, have no effect on rendering?

As for the raw mode, it is not meant to edit RTL text. It is meant to preview mixed LTR+RTL content the way it is stored, and to edit tags and placeholders (which are LTR). So this is by design.

We'll see what we can do with the carriage return symbols. Probably will find some similar unused WS symbol.

**Comment by khaledhosny** [comment]
The current raw mode is usable for Arabic, but the new one is completely unintelligible and I don’t see what much value this uninhabitability brings. And having the text shaped while being forced LTR just adds salt to the injury. If it were unshaped it would have been at least clear that it is bring broken intentionally.

**Comment by iafan** [comment]
I think for `LF` symbol, we can replace reqular line feed symbol:
`000A;<control>;Cc;0;B;;;;;N;LINE FEED (LF);;;;`

with this one (the same control character that bears the same semantics and BiDi class):
`0085;<control>;Cc;0;B;;;;;N;NEXT LINE (NEL);;;;`

I don't believe it is widely used (especially in localizable strings).

@dwaynebailey @khaledhosny thoughs?

**Comment by khaledhosny** [comment]
I already gave sample text few comments up.

**Comment by khaledhosny** [comment]
Leading and trailing spaces are rendered as dashes, as well as more than one space on the middle of text. Single space in the middle is fine.

**Comment by iafan** [comment]
> And having the text shaped

Do you mean here that it is rendered in monospace font?

**Comment by iafan** [comment]
> Leading and trailing spaces are rendered as dashes

Can you please provide a screenshot?

**Comment by khaledhosny** [comment]
Here is a screenshot of the spaces:
![2016-04-27 22-50-59](https://cloud.githubusercontent.com/assets/93914/14867802/f34bec3a-0cd2-11e6-9808-71f3de5fc9ca.png)

And here is word in regular mode, Arabic for shoulder:
![2016-04-27 22-51-51](https://cloud.githubusercontent.com/assets/93914/14867833/273a0644-0cd3-11e6-86c8-d6a247ff6d55.png)

And in raw mode it reads kill, destroy:
![2016-04-27 22-52-11](https://cloud.githubusercontent.com/assets/93914/14867867/52d3d0b4-0cd3-11e6-8ec8-53428272fae6.png)

If one insists on forced LTR mode (which I’d really hate), at least make the text unshaped:
![2016-04-27 22-56-27](https://cloud.githubusercontent.com/assets/93914/14867923/ae43e65a-0cd3-11e6-901a-8c79c3b94177.png)

**Comment by iafan** [comment]
@khaledhosny Ok. So it seems that your default font does have a symbol for the Ogham space mark, which is rendered as a dash, and thus doesn't take the glyph from the Raw font that we use (which has it rendered as a dot). But otherwise this symbol (dash) doesn't affect the directionality of the adjoining text, correct?

I understand what you mean by unshaped now, and our intent for Raw mode was to do exactly that — display all raw symbols separately. Not sure how to achieve that easily, though. The only thing that comes to mind is to insert an invisible space (or thin space) between all symbols dynamically.

**Comment by iafan** [comment]
I also checked with our own developer here who speaks Arabic and ran a demo through him: he has no "dash instead of the dot" issue. So I guess this is specific to a particular system/browser (but I believe we will be able to resolve this specific issue). He also confirmed that this tiny dot doesn't get in the way and doesn't break the flow of the RTL text in any way.

His opinion on Raw mode is that it is not mean to be used by translators (when they are doing the actual translation of the text), and to review placeholders the raw mode is totally fine, even with symbols shaped together. Yes, in some rare circumstances you will get an unintentional meaning (like if you're writing the word "dog", switch to a raw mode and can read the word "god" between other symbols, but that is ok and is pretty rare). So he thinks that trying to break symbol shapes apart would unnecessary complicate the engineering for not much of a benefit. Again, nobody is supposed to be writing _text_ in this mode, because there's a regular mode for that. It's only about reviewing placeholders and special non-printable BiDi control symbols.

As for the `LF` symbol displayed incorrectly near numbers, we could reproduce this, but he saw that as a pretty minor issue (not something really breaking the flow, and not something we should write robust directionality detection algorithms for).

Just a separate opinion of a native speaker to get the fuller picture.

**Comment by khaledhosny** [comment]
I don’t think my default font has a glyph for Ogham space (I just checked, it doesn’t).

**Comment by khaledhosny** [comment]
I think the simple fix is to not force LTR text direction, because current raw mode works just fine and I have been using it probably since it was introduced for the situations like what you just described. So far no one has explained to me why we need forced LTR here.

**Comment by iafan** [comment]
> I don’t think my default font has a glyph for Ogham space (I just checked, it doesn’t).

What OS/browser/version do you use (just for the record)? Does the same issue appear if you use some other browser?

> I think the simple fix is to not force LTR text direction, because current raw mode works just fine

It was historically in a semi-implemented state that did render Arabic correctly but not the placeholders (when you have a mix of Arabic and e.g. HTML tags or placeholders with some punctuation marks). Now it will do what it was originally supposed to do, and yes, it will intentionally break RTL flow, and you will now have a choice whether to edit/review the text itself (in the regular mode) or review placeholders (in Raw mode).

**Comment by khaledhosny** [comment]
Firefox on Linux, no other browsers to test with at the moment.

Do you have a text that does not currently work in raw mode, because I was just using it for that. Without being able to read the words its usability for me it reduced to the simplest of cases, I need to know which words I’m inserting the placeholders between or how can I validate it is the correct place? With no shaping at all I can train myself to read the text backwards, but with shaping this is nearly impossible (for me at least).

**Comment by iafan** [comment]
> Do you have a text that does not currently work in raw mode

Yes, consider this example:

This is how the text is displayed in regular mode (tags appear broken):
![c](https://cloud.githubusercontent.com/assets/1728158/14870451/47928ad6-0c8f-11e6-9bea-b1449c215571.png)

And this is the text is displayed in Raw mode with no forced LTR (still broken):
![b](https://cloud.githubusercontent.com/assets/1728158/14870404/fd367f6a-0c8e-11e6-9f12-ef151b4e6534.png)

This is how the text renders currently in Raw mode with forced LTR (you can verify that tags are not broken):
![a](https://cloud.githubusercontent.com/assets/1728158/14870395/ebd4290c-0c8e-11e6-97ac-31cbda68732d.png)

With forced LTR, there's also no caret quirkiness — you can predictably select/copy/paste/move mixed LTR+RTL chunks.

This what the Raw mode is about. Switching between Raw and normal mode gives you a degree of freedom when dealing with such strings. Translators are not expected to use Raw mode by default or try to read/review text while in this mode.

**Comment by khaledhosny** [comment]
Oh, XML. OK I don’t edit much XML during translation to encounter such a case, and though I don’t think forced LTR is the proper fix here (treating XML tags as bidi isolates should be the fix), I understand it is the simplest solution.

To prevent the shaping you can add something like this to the CSS rules:
```css
font-feature-settings: "isol" off, "init" off, "medi" off, "fina" off;
````

**Comment by iafan** [comment]
I agree there's a way to display both tags and RTL properly, but this requires some heavy Unicode analysis and will likely require writing a completely custom editing control, which we can't afford doing at the moment.

> `font-feature-settings: "isol" off, "init" off, "medi" off, "fina" off;`

Thanks for the suggestion! I quickly tested this and this is what I've got in Raw mode (just to verify that this is what you would expect):
![d](https://cloud.githubusercontent.com/assets/1728158/14871138/85803ca8-0c94-11e6-9af2-3b2edd433e57.png)

We can definitely add this to the CSS styles.

**Comment by iafan** [comment]
We can also add `letter-spacing: 0.1em;` to visually separate symbols a bit in this mode:
![e](https://cloud.githubusercontent.com/assets/1728158/14871188/fc43177a-0c94-11e6-8db5-7cfbc8e73a5f.png)

Let me know if you feel it looks better this way.

**Comment by khaledhosny** [comment]
I don’t think the extra spacing is needed in general, looks like Courier New have bad spacing here, bit not all Arabic monospace fonts are like that.

**Comment by iafan** [comment]
Ok, so we'll go only with `font-feature-settings: "isol" off, "init" off, "medi" off, "fina" off;` for now, then (cc @julen)

**Comment by iafan** [comment]
@khaledhosny if you're comfortable with the developer console in your browser, do you mind opening the CSS styles for the editor textarea in Pootle and changing `font-family: sans-serif, "Raw";` to `font-family: "Raw", sans-serif;` and see if this changes your "dash" symbol for spaces to a tiny dot one?

**Comment by khaledhosny** [comment]
Swapping the order of fonts makes the small dot appear indeed. It still does not appear for single space in the middle of text (no dash either, just the regular space).

**Comment by iafan** [comment]
That's expected. In regular mode, we will only show dots for duplicate whitespace and leading/trailing spaces.

**Comment by julen** [comment]
> That's expected. In regular mode, we will only show dots for duplicate whitespace and leading/trailing spaces.

To add on top of this, note the small dots replace the current red squiggles, which make it very hard to distinguish the number of spaces they represent.

**Comment by julen** [comment]
> @khaledhosny Ok. So it seems that your default font does have a symbol for the Ogham space mark, which is rendered as a dash, and thus doesn't take the glyph from the Raw font that we use (which has it rendered as a dot).

@iafan if we want to ensure the best experience, we have to specify font families in the `"Raw", sans-serif` order, otherwise we have the risk of ending up with issues like @khaledhosny ran into.

Having `"Raw", sans-serif` means we are back with the small caret, however I checked on the topic and this can be solved in the font itself: caret height seems to be a function of font-size, and font-size is influenced by the ascent and descent of the specific font. Since the glyphs in the raw font are quite short compared to the _standard_ sans-serif font glyphs, this results in smaller ascent/descent values, hence the smaller caret height.

So the solution would be (disclaimer: I'm not a font expert) to either adjust the font properties to have higher ascent/descent values, or introduce a glyph which would result in having higher ascent/descent. I tried this with a simple font editor and it worked, so you will want to adjust the font get an acceptable caret size. It might be a good idea to play around by mixing the raw font with different font families, too.

**Comment by julen** [comment]
By the way @iafan, it would be great to experiment converting the TTF font to WOFF, which from my understanding should offer a better compression gain.

**Comment by julen** [comment]
I just updated the PR code to include the suggested `font-feature-settings` properties in raw mode, and have put the font families in `"Raw", sans-serif` order to prevent potential issues like displaying glyphs from other fonts for our special characters.

Looking forward to the next font update @iafan.

**Comment by julen** [comment]
Got the requested font update via email from @iafan and the PR has been updated accordingly. Other assorted fixes have been pushed as well.

**Comment by dwaynebailey** [comment]
@iafan @julen I'd like to invite RTL localisers to have a look at this.  But hit the following concerns with staging.  We don't have a project that just highlights the special features of the PR, space behaviour, font, etc. You kind of have to find them.

So could we build a demo project that actually highlights:

1. The workings - I shared my test
2. Potential problem areas - variables, HTML, etc.

At the moment I fear anyone I point to staging to test, won't even know what to test or how to find good examples.  And we really need them to be testing behaviour in good examples to get buyin or to pick up any potential issues.

**Comment by iafan** [comment]
Bringing essentials from the conversation in Gitter:

1. We created a small test project to play with: https://translate.stage.evernote.com/projects/_test_raw_font/

2. We currently display `\r` as `[CR]` symbol, but don't have a good support for it in terms of editing. I think we should isolate translators from intricacies of platform-dependent newline encoding, and the proper way of dealing with this is at a parser level, not at unit editing (since the type of line endings is a property of an entire file, and all line endings should be encoded consistently throughout the file). In Pootle, all newlines must always be encoded as `\n`. I suggest moving this into another issue, and not tie to this PR.

**Comment by iafan** [comment]
@julen one new regression I spotted is that in read-only units (table rows other than the unit editor) we started to visually emphasize placeables, and because of the increased cell height it now shows a vertical scrollbar. See how em dash ("—") is rendered in the rows on this page: https://translate.stage.evernote.com/ru/android_evernote/translate/#search=%E2%80%94&sfields=source,target

I think we don't need to render certain parts of the string as placeables in such rows.

**Comment by 5y** [comment]
Hi, My result about Persian(RTL language) and Bidi:
1- I Can't Use tab
2- Dot(.) for space works fine and Also we can define sign for [ZWNJ](https://en.wikipedia.org/wiki/Zero-width_non-joiner) I can't find any Sign for it, usefull for RTL language.
3- About NBSP I got follow Result[1]


[1] ![image](https://cloud.githubusercontent.com/assets/1941933/15302653/518c37f0-1bc9-11e6-949d-faec383cf85c.png)

**Comment by dwaynebailey** [comment]
> We currently display \r as [CR] symbol, but don't have a good support for it in terms of editing. I think we should isolate translators from intricacies of platform-dependent newline encoding, and the proper way of dealing with this is at a parser level, not at unit editing (since the type of line endings is a property of an entire file, and all line endings should be encoded consistently throughout the file). In Pootle, all newlines must always be encoded as \n. I suggest moving this into another issue, and not tie to this PR.

@iafan, while I agree we want to isolate translators I think your assumptions are incorrect.

1. These escapes are actually valid in some localisation formats, we can't pretend that they don't exist.
2. The parser in some instances is not able to deal with this.  When do we convert \n in Pootle to \r\n in the target format?  The whole project, some files, the whole file, part of the file, a single unit?
3. Until the parsers have this sort of contract with Pootle and Pootle is able to manage such contract we can't just drop this.
4. Not addressing this issue here, makes Pootle undeployable.  And the other route of making parsers able to manage the various escapes towards \n needs way more work and time.

**Comment by iafan** [comment]
@dwaynebailey yes, I understand that some files may come with Windows-specific endings, and Pootle needs to deal with them. I want to say that the only way to properly deal with them is on the _file_ level, not on the _unit_ level. Most of the units will not have a hard line break in the string, so you will never know what to insert in the translation — `\r\n` or just `\n` — it is the file (the parser) that only knows it. The way it currently works in Pootle is prone to breaking the final localized file by encoding line breaks  inconsistently.

Until this is properly implemented, I believe that what we currently do (display `\r` as a special visible `[CR]` box, allow to copy-paste it, save in the unit properly) keeps the level of support at the same level as we have it currently in Pootle. So let's focus on `[CR]` handling issues, if there are any.

**Comment by iafan** [comment]
@5y did you type `&nbsp;` or did you just copy-paste the `[nbsp]` symbol from the source string?

I tried to do the latter, and it seems that it works correctly this way. [Can you please check](https://translate.stage.evernote.com/fa/_test_raw_font/translate/test.po#unit=5626979)?

**Comment by iafan** [comment]
> Also we can define sign for ZWNJ I can't find any Sign for it, usefull for RTL language.

@5y you can insert ZWNJ symbol into your translation (there's a set of buttons to insert such such symbols beneath the textarea), but it is supposed to be visible only in Raw View. If you toggle the 'Raw View' button (the button next to 'Show Tineline' one), you will see all your special symbols displayed in there.

**Comment by dwaynebailey** [comment]
@iafan I'm afraid you are making the assumption that these escapes will be consistent through the file.  There is no guarantee that this will be true.

I'm really not sure what you mean by Pootle encoding the break inconsistently.  Its behaviour currentlyis very consistent.

Doing `\r` as `[CR]` displays now, but there are some problems that I've reported previously.  Doing `\r` as a single `[CR][LF]` seems like a more sensible solution to me as it forces translators to be consistent with what the unit expects in terms of newlines.

**Comment by iafan** [comment]
But why do you assume that `\r\n` will always stick together as a sequence? Technically one can use `\r` alone as some sort of separator. Currently Pootle does allow you to use `\r` and `\n` independently. If we make an assumption that `\r\n` should always go together, then the new editor will not support some cases the current editor does.

Also, if line breaks are unit-specific, how does Pootle know what sequence to use if one wants to use an explicit line break in the translation? How is Pootle currently consistent about this? I can easily add any sequence of `\r` and '\n' while translating the string.

**Comment by dwaynebailey** [comment]
@iafan my assumption of `\r\n` is based on seeing this in the wild.  While you are right it can occur anywhere, I've never seen it.  If the aim is to make translators lives easier I would suggest that `\r\n` be seen as one character, that does not preclude a single `\r` being treated as such.  But I'm not attached to this solution, it's just that it makes it very clear what line ending is required and it's a single click.

The last point is a perennial problem. And I think you miss my point that there is the real likelihood that a file has multiple newline styles, so the parsers and file formats can't always know what this should be.  HTML can be snuck into JS.  Windows messages into Unix PO files.  So we are able to deal with the cases where the newline already exists, but we can't really deal with cases where one does not exist.  And yes they're likely consistent across a file.... except when they aren't.

The bottom line for me is this, I'm not sure we can solve that, even if we do it's not part of this problem.  But `\r\n` is a part of this problem and we need to solve it as part of this issue.

**Comment by iafan** [comment]
I was proposing a pretty straightforward fix: unconditionally replace `\r\n` with `\n`. Such normalization doesn't break anything, simplifies the workflow and will protect developers from hard-to-catch issues with files having mixed line endings. This is what we've been doing internally for many years without any single issue.

We can hack the editor to do the following:

1. detect if there's a `\r\n` sequence in the source string. If there is, raise the `hasCRLFEndings` flag.
2. replace all `\r\n` with `\n` before editing. Users will see linebreaks as simple `[LF]` symbols (in other words, they will be isolated from the differences in line endings, and the editor will work as expected.
3. Before submitting the translation, if `hasCRLFEndings` flag is raised, convert all lone `\n` to `\r\n`.

So in the output units, their line endings will be preserved to our best knowledge, but in Pootle people will never deal with different kinds of line endings.

**Comment by dwaynebailey** [comment]
@iafan simply replacing `\r\n` with `\n` is not a straightforward fix.  Lets not confuse your specific workflow with the general Pootle user's workflow in which the format does not know about such escaping plans and where both are valid in the format.

I'm all for unifying the info to localisers.  I'm just not 100% sure why we're trying to solve this issue here and now.  This PR already has enough scope, I really don't think we want to scope creep here.

I can see your proposal working for most cases I've seen.  But I don't think this is the right time and place to land such a fix that could break other things.

But please, we've just asked for feedback from a number of users.  This discussion shouldn't be clouding this issue here and now.

**Comment by 5y** [comment]
@iafan I just type &nbsp; , Yes and what about the tab?

**Comment by iafan** [comment]
@5y thanks. We'll look into this. I don't think there's a way to insert tabs in Pootle (but if the source string contains a tabulation symbol, you can copy-paste it). We could think of the alternative shortcut to insert tabs, because just using Tab key is better be reserved for navigation between controls.

**Comment by dwaynebailey** [comment]
@iafan should we at least make the raw font characters clickable?  Inserting things like NBSP and TAB via copy-paste doesn't seem ideal.  We allow clicking on special non-ascii character, I wonder if we can duplicate that functionality for these?

**Comment by julen** [comment]
@5y I'm typing a non-breaking space with the physical keyboard, using <kbd>alt+space</kbd> in Mac, along with some text in Arabic script and I can properly see the `NBSP` symbol both in the textarea and the suggestion box. I tried in Chrome, Safari and Firefox and I cannot reproduce the problem. It'd be good to know which steps you followed so we can diagnose what happened.

**Comment by julen** [comment]
> @julen one new regression I spotted is that in read-only units (table rows other than the unit editor) we started to visually emphasize placeables, and because of the increased cell height it now shows a vertical scrollbar. See how em dash ("—") is rendered in the rows on this page: https://translate.stage.evernote.com/ru/android_evernote/translate/#search=%E2%80%94&sfields=source,target
> I think we don't need to render certain parts of the string as placeables in such rows.

This should now be fixed; you can use the previous link to validate it.

**Comment by dwaynebailey** [comment]
@julen I notice that the 'previous translations' are now side-by-side instead of stacked as it was previously.  As in https://translate.stage.evernote.com/ru/android_evernote/translate/#search=%E2%80%94&sfields=source,target

Was that intended?

**Comment by iafan** [comment]
See also a related issue: https://github.com/translate/pootle/issues/4739 (undo/redo stack doesn't work properly when we insert placeables) which becomes more prominent with our new editor.

**Comment by julen** [comment]
@dwaynebailey it's partly intended and it's been [around since the very early stages](https://github.com/translate/pootle/pull/4171/commits/98510783d6ac120dddce5551e0ec94bd8f4cc875) ([and even validated](https://github.com/translate/pootle/issues/3941#issuecomment-157951332), it seems). I was under the impression [I provided some comment](https://github.com/translate/pootle/issues/3941#issuecomment-159093393) about it, although I see I didn't go into the details of this specific change as the commit did.

Since new lines characters incur in line breaks in HTML, and taking into account the previous layout displays texts inline, the result would be garbled, that's why source/target texts need to be displayed as block-level elements.

While on it, the vertical split was chosen based on observing results for a while, considering it offered a clearer picture of the match.

Another option of course is to split blocks horizontally, which would vertically align texts, however this would also leave translated texts at the bottom, farther away from the translator's eyes, even requiring to scroll in some cases, and adds up more vertical space for short texts.

Feel free to play with results by adjusting the CSS declaration for `.suggestion-wrapper` and adding the `flex-direction: column;` rule to it, so you get to feel the horizontal split. I don't have strong feelings and I'm happy to switch this to the horizontal split that's what we all prefer, note however that either way there needs to be a compromise.

**Comment by dwaynebailey** [comment]
@julen it's easy to miss and I fear my short string test file would have masked these anyway.  Some aspects of my review are only happening now as the PR stabilizes.

I'm not attached to any of the renderings, though I've gotten used to above/below.  I suspect that your comment re left/right, that "*it offered a clearer picture of the match*", is correct in that all the info on the left is about matches so you can parse that easily without it being clouded by the translation.

I couldn't figure out the test instructions I'm afraid.  So for now assume I'm OK with left/right based on your comment.

**Comment by julen** [comment]
In order to test the horizontal split rendering you need to edit _editor.css_ (either on the FS or directly in your browser) and add `flex-direction: column;` at the end of the `.suggestion-wrapper` section.

**Comment by dwaynebailey** [comment]
@julen thanks for the pointers, managed to change that on the staging server.  I concur, two columns makes it much easier to see the differences of all the suggested units from the source text, making it easier to make a selection.

**Comment by khaledhosny** [comment]
I’m testing on https://translate.stage.evernote.com/ar and the first thing I noticed is that the text area is left aligned, is this intentional?

**Comment by khaledhosny** [comment]
It seems that not only the text is aligned left, but also the direction is ltr which breaks the order of any text with mixed directionality.

**Comment by iafan** [comment]
@julen, @khaledhosny is right: directionality is broken in the current PR. Looks like a regression.

**Comment by julen** [comment]
Thanks for the heads-up folks, the context required to retrieve the language information was lost in the last commit and this is now fixed.

**Comment by khaledhosny** [comment]
OK, looks good now. Doing more testing I found that <RTL><tab><numbers> is rendered as <RTL><numbers><tab>, using e.g. `واحد	١٢٢٢٢`:
![2016-05-23 12-19-14](https://cloud.githubusercontent.com/assets/93914/15467812/13920f2c-20e9-11e6-802f-158e735f7d1f.png)

**Comment by khaledhosny** [comment]
The same with NBSP as well.

**Comment by julen** [comment]
Thanks for testing again @khaledhosny. @iafan we will need to do the same we did with new lines: find a spare character with the same strength as the actual character being replaced and use that in our raw font for the symbols. This applies to the symbols displayed in regular mode, which at the moment are <kbd>NULL</kbd> (`\u0000`), <kbd>TAB</kbd> (`\u0009`), <kbd>ESC</kbd> (`\u001b`), <kbd>NBSP</kbd> (`\u00a0`) and <kbd>LF</kbd> (`\u000a`, already covered). For specific details, please refer to [the character table](https://github.com/translate/pootle/issues/3941#issuecomment-176243740) in this same thread.

**Comment by dwaynebailey** [comment]
This site http://www.sql-und-xml.de/unicode-database/bidi-cs.html might help in terms of finding Unicode characters that are in the same class.

Someone might need to remind me why we can't just draw glyphs for the real code points :/

**Comment by iafan** [comment]
> Someone might need to remind me why we can't just draw glyphs for the real code points :/

From my prior experiments, browsers (or Browser+OS-level font rendering libraries) have strong feeling about certain characters, and don't allow to render any arbitrary glyphs in place of them. Firefox is the most tricky browser in that respect, as many glyphs, being rendered properly in Chrome or IE, are not displayed in FF.

**Comment by julen** [comment]
@iafan provided me an updated font which remaps the control characters in regular mode to their [control picture](https://en.wikipedia.org/wiki/Unicode_control_characters#Control_pictures) counterparts, which have the same strength as the original characters, and the code has been updated to use that. With this as I see the issue with <kbd>TAB</kbd> (and <kbd>NBSP</kbd> etc.) reported earlier is now fixed.

_(Note: if you are using Firefox and are experiencing problems when testing the font, you might need to restart the browser — we have observed it caches fonts very aggressively.)_

**Comment by dwaynebailey** [comment]
Thanks @julen and @iafan 

Doing some clicky testing.

@julen not sure if Undo stack is part of this? If not.  Doing lots of edits and then undoing make a pretty amazing mess in RTL.

* CR+LF rendering is incorrect in source see https://translate.stage.evernote.com/af/_test_raw_font/translate/test.po#unit=5626939&offset=0
* CR+LF in source missing CR char if its in the middle https://translate.stage.evernote.com/af/_test_raw_font/translate/test.po#unit=5626940&offset=0
* CR+LF creates a double return which seems odd.

**Comment by iafan** [comment]
Neither CR+LF handling nor undo stack is a part of this update. Just formal symbol rendering in RTL.

**Comment by julen** [comment]
I pushed another update which deals with undo/redo (our staging server is up-to-date in case someone wants to give it a shot).

**Comment by iafan** [comment]
@julen Undo/redo seems to work correctly (including the cases when placeables are inserted). 

I noticed some strange behavior with copy-pasting, though:
1) Open https://translate.stage.evernote.com/af/_test_raw_font/translate/test.po#unit=5626935
2) Select the first symbol of the translated text (`E`), copy, then paste it.

On pasting, the trailing newline will be gone.

**Comment by julen** [comment]
Thanks for the report @iafan, I hope to have a fix for it soon.

**Comment by julen** [comment]
> Thanks for the report @iafan, I hope to have a fix for it soon.

I spent part of today debugging this issue, and it turns out it happens in Chrome and Safari and only when cutting is used before. I couldn't draw more conclusions unfortunately: for some obscure reason, when the paste happens and the `change` event is triggered, the textarea in Chrome/Safari's DOM is missing the final `\n` in its value. If I add a character after `\n`, I cannot reproduce the issue anymore.

In the mean-time, I also added support for clicking in the raw font symbols.

**Comment by dwaynebailey** [comment]
@julen did some undo testing and got the some positive results and anomaly as @iafan.  Did quite a bit of changing and altering.  I got some strange results in RTL, but I was using Latin in RTL, so would prefer an RTL user to comment.

**Comment by dwaynebailey** [comment]
@julen picked up an issue with clickable font symbols (nice addition though)

1. Using https://translate.stage.evernote.com/af/_test_raw_font/translate/test.po#unit=5626949&offset=0
2. Delete and add manually including manual entry on NBSP, works
3. Delete, type "Foo", click on NBSP to insert, type "bar"
4. Click submit.  "bar" is removed from entry, sticks on that unit, "Submit" button greys out

Hope that allows you to replicate.

**Comment by julen** [comment]
I believe this last issue you reported is now fixed @dwaynebailey.

**Comment by dwaynebailey** [comment]
@julen confirmed fixed

**Comment by julen** [comment]
Yet another update: now `\r\n` is handled transparently, normalizing it internally in the client-side code to `\n`. Translators can still input individual `\r` characters by using the mouse. Our staging server, as well as the test file, have been updated accordingly.

With this in place, I believe we are close to considering the work here as finalized. As a missing bit, I still haven't figured out the [pasting issue reported earlier](https://github.com/translate/pootle/issues/3941#issuecomment-222750762), and I have the feeling it might be some race condition but I still need to check that again.

**Comment by dwaynebailey** [comment]
@julen tested on staging and this works from the user side of the equation, can't test the source file.

**Comment by julen** [comment]
#4171 is now merged, so closing this one.
