### ISSUE TITLE
New editor: Extra blank "Insert space symbol" buttons

### ISSUE THREAD

**Issue by gunchleoc** [translate/pootle#5399]
In the new editor, gd locale, we are getting some extra buttons below the text area, with the tooltip "Insert space symbol into the editor"

Screenshots of old and new, with the extra buttons outlined in red:

![space-symbol-buttons](https://cloud.githubusercontent.com/assets/4095570/19514801/e0c39eac-95ec-11e6-9369-d479cae84a2d.png)

**Comment by unho** [comment]
This was due to empty space character separating the actual symbols for gd in MLO (the symbols are specified in a string).

This is now fixed.

**Comment by gunchleoc** [comment]
Thanks for fixing both my bugs :)

When will this be live for testing?

**Comment by gunchleoc** [comment]
Hm, that link points to the old editor, where this issue wasn't present anyway.

**Comment by unho** [comment]
Changed too in that testing environment.

**Comment by gunchleoc** [comment]
The bug is still there:

![buttons-pootle](https://cloud.githubusercontent.com/assets/4095570/19644083/c108687a-99e5-11e6-9aa5-695211b96e8a.png)

**Comment by unho** [comment]
That looks like the testing setup that might have got changed in the last days, so my changes probably got lost. But don't worry, that just is a testing server.

**Comment by gunchleoc** [comment]
OK, good to know - let me know if you need any more testing on this :)

**Comment by unho** [comment]
No further testing needed since this has been refactored to prevent this from ever happening again. Thanks a lot.
